spring:
  application:
    name: consumer
  hystrix:
    enabled: true

server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: '{cipher}AQBzdtUpigYU/2uH6ywIlWh/uy/bbGW8tR9pKU4BsYxyN4VqkudWYJ6vrtfh8brO/EPvCfcQv8xbIWjLEnO9UWRW05MEfyhuosq5jMd2bI3RtX9BCUXxqKnN3fxzOCbHPMkRL633L+UwYhThR/XrBhTM+lx7TH8oE32xOdwNaRzCdDSNgKpdqjJs9AMNBJe0ZQ+4Y4OvAETr2T/h3+EuuisDFn5OUaY6zkaExqofad26fYTr9znNbxQ6vt+00Z4oacAqjKupGfFgeICRZqG8Pl1Ae9yM5OAdtxG6sVjhGM9uJLo0BQwN9XZ4f8PGMjjhgy3igCKWmsPkqk6sqm2PNva4vyqfCxC8MsPjkbEA8sokliRfGIIeuBV4YQurV3kxfKWAC8VFVgdLQMpHUEs6XOx8K+mhbuTUR27D2/mlhy8Boebs0YW6fzDJMZh9yEwV21EKifqhgN8KzYzcwr5iq8yB'
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 10000

  gateway:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
        timeout:
          enabled: true









